name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS:${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest]
        include:
          - os: windows-latest
            node-version: 16
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn lint
        if: matrix.os != 'windows-latest'
      - run: yarn typecheck
      - run: yarn test --coverage
      - run: npx codecov
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.node-version == 16
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: test
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "16"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
