name: Node.js CI

on: [push]

jobs:
  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
